// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFElac6n4pYqxaXLKctBKkF9IluxtuKec',
    appId: '1:653357841440:web:9be2803d4654fea47c5045',
    messagingSenderId: '653357841440',
    projectId: 'gnbtask',
    authDomain: 'gnbtask.firebaseapp.com',
    storageBucket: 'gnbtask.firebasestorage.app',
    measurementId: 'G-B92494SEF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGJDfLbdY8gLd46uz1PsRr5jwcYSVf_U',
    appId: '1:653357841440:android:dfb42bfb29cf0c917c5045',
    messagingSenderId: '653357841440',
    projectId: 'gnbtask',
    storageBucket: 'gnbtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6t8_VQmPaI4GAgymx7TzqJzA7lKQR5E',
    appId: '1:653357841440:ios:d479e372efc0729b7c5045',
    messagingSenderId: '653357841440',
    projectId: 'gnbtask',
    storageBucket: 'gnbtask.firebasestorage.app',
    iosBundleId: 'com.example.gnbtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo6t8_VQmPaI4GAgymx7TzqJzA7lKQR5E',
    appId: '1:653357841440:ios:d479e372efc0729b7c5045',
    messagingSenderId: '653357841440',
    projectId: 'gnbtask',
    storageBucket: 'gnbtask.firebasestorage.app',
    iosBundleId: 'com.example.gnbtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFElac6n4pYqxaXLKctBKkF9IluxtuKec',
    appId: '1:653357841440:web:2f9ad645f74f6f497c5045',
    messagingSenderId: '653357841440',
    projectId: 'gnbtask',
    authDomain: 'gnbtask.firebaseapp.com',
    storageBucket: 'gnbtask.firebasestorage.app',
    measurementId: 'G-RMJ1PGMVKJ',
  );
}
